# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_server.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11grpc_server.proto\x12\x12\x63ore.communication\"\x07\n\x05\x45mpty\"\x19\n\tBlockData\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"k\n\x05\x42lock\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x15\n\rprevious_hash\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\r\n\x05nonce\x18\x05 \x01(\x05\x12\x0c\n\x04hash\x18\x06 \x01(\t\"<\n\x0f\x42lockchainState\x12)\n\x06\x62locks\x18\x01 \x03(\x0b\x32\x19.core.communication.Block\" \n\rBlockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xb0\x01\n\nBlockchain\x12T\n\x12GetBlockchainState\x12\x19.core.communication.Empty\x1a#.core.communication.BlockchainState\x12L\n\x08\x41\x64\x64\x42lock\x12\x1d.core.communication.BlockData\x1a!.core.communication.BlockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=41
  _globals['_EMPTY']._serialized_end=48
  _globals['_BLOCKDATA']._serialized_start=50
  _globals['_BLOCKDATA']._serialized_end=75
  _globals['_BLOCK']._serialized_start=77
  _globals['_BLOCK']._serialized_end=184
  _globals['_BLOCKCHAINSTATE']._serialized_start=186
  _globals['_BLOCKCHAINSTATE']._serialized_end=246
  _globals['_BLOCKRESPONSE']._serialized_start=248
  _globals['_BLOCKRESPONSE']._serialized_end=280
  _globals['_BLOCKCHAIN']._serialized_start=283
  _globals['_BLOCKCHAIN']._serialized_end=459
# @@protoc_insertion_point(module_scope)
