---
apiVersion: v1
kind: Secret
metadata:
  name: dai-secrets
  labels:
    app: dai-system

type: Opaque
data:
  jwt-secret-key: c3VwZXJzZWNyZXRrZXk=  # Base64 encoded secret key for JWT
  db-username: YWRtaW4=  # Base64 encoded database username
  db-password: cGFzc3dvcmQ=  # Base64 encoded database password
  kms-key: ZGFpa2V5bWFuYWdlbWVudHNlY3JldA==  # Base64 encoded KMS key for encryption

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  labels:
    app: dai-system

type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tLQo=  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tLQo=  # Base64 encoded private key
