# Security Configuration for Decentralized AI System

# General security settings
security:
  enable_zero_trust: true  # Enable Zero Trust Architecture for security
  enforce_strong_authentication: true  # Require strong authentication for all system components
  jwt_secret_key: "supersecretkey"  # Secret key for JWT authentication
  jwt_expiry_minutes: 60  # Token expiration time in minutes
  allowed_hosts:  # Hosts that are allowed to access the system
    - "localhost"
    - "192.168.1.0/24"

# SSL/TLS settings
ssl:
  enabled: true
  certificate_path: "configs/certs/server_cert.pem"
  private_key_path: "configs/certs/server_key.pem"
  enforce_ssl: true  # Force all communications to use SSL/TLS

# Encryption settings
encryption:
  enabled: true
  encryption_algorithm: "AES-256"  # Encryption algorithm for secure data storage and transfer
  key_management_service: "kms_service"  # Key management service to handle keys securely
  keys:
    public_key_path: "configs/keys/public_key.pem"
    private_key_path: "configs/keys/private_key.pem"

# Authentication settings
authentication:
  enabled: true
  jwt_algorithm: "HS256"  # JWT signing algorithm
  multi_factor_authentication:
    enabled: true
    sms_provider: "twilio"  # SMS provider for MFA

# Authorization settings
authorization:
  role_based_access_control: true  # Enable role-based access control (RBAC)
  roles:
    - name: "admin"
      permissions: ["read", "write", "delete", "manage_users"]
    - name: "user"
      permissions: ["read", "write"]
    - name: "guest"
      permissions: ["read"]

# Network security settings
network:
  firewall:
    enabled: true
    allowed_ports:
      - 80   # HTTP
      - 443  # HTTPS
      - 50051  # gRPC
  ddos_protection:
    enabled: true
    max_requests_per_second: 100  # Maximum requests allowed per second

# Monitoring and alerting settings
monitoring:
  enabled: true
  intrusion_detection_system:
    enabled: true
    alert_threshold: 5  # Number of suspicious activities before alert is triggered
  log_security_events: true  # Log security-related events for auditing purposes

# Logging settings
logging:
  log_level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file_path: "logs/security.log"
  log_retention_days: 30

# Secure storage settings
secure_storage:
  enabled: true
  encryption_enabled: true  # Encrypt all sensitive data at rest
  storage_backend: "vault"  # Backend to store sensitive data securely

# Miscellaneous settings
misc:
  auto_patch_vulnerabilities: true  # Automatically patch known vulnerabilities
  periodic_security_audit:
    enabled: true
    audit_interval_days: 30  # Interval for running security audits in days
